export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const VERIFY = "VERIFY"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_FAILED = "VERIFY_FAILED"

export const FETCH_USER = "FETCH_USER"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILED = "FETCH_USER_FAILED"

export const ADD_USER_PROFILE = "ADD_USER_PROFILE"
export const ADD_USER_PROFILE_SUCCESS = "ADD_USER_PROFILE_SUCCESS"
export const ADD_USER_PROFILE_FAILED = "ADD_USER_PROFILE_FAILED"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED"

export const FETCH_DASHBOARD = "FETCH_DASHBOARD"
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS"
export const FETCH_DASHBOARD_FAILED = "FETCH_DASHBOARD_FAILED"

export const ADD_INCOME = "ADD_INCOME"
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS"
export const ADD_INCOME_FAILED = "ADD_INCOME_FAILED"

export const FETCH_INCOME = "FETCH_INCOME"
export const FETCH_INCOME_SUCCESS = "FETCH_INCOME_SUCCESS"
export const FETCH_INCOME_FAILED = "FETCH_INCOME_FAILED"

export const INCOME_DETAIL = "INCOME_DETAIL"
export const INCOME_DETAIL_SUCCESS = "INCOME_DETAIL_SUCCESS"
export const INCOME_DETAIL_FAILED = "INCOME_DETAIL_FAILED"

export const DELETE_INCOME = "DELETE_INCOME"
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS"
export const DELETE_INCOME_FAILED = " DELETE_INCOME_FAILED"

export const EDIT_INCOME = "EDIT_INCOME"
export const EDIT_INCOME_SUCCESS = "EXIT_INCOME_SUCCESS"
export const EDIT_INCOME_FAILED = "EDIT_INCOME_FAILED"

export const FETCH_EXPENSE = "FETCH_EXPENSE"
export const FETCH_EXPENSE_SUCCESS = "FETCH_EXPENSE_SUCCESS"
export const FETCH_EXPENSE_FAILED = "FETCH_EXPENSE_FAILED"

export const ADD_EXPENSE = "ADD_EXPENSE"
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS"
export const ADD_EXPENSE_FAILED = "ADD_EXPENSE_FAILED"

export const EDIT_EXPENSE = "EDIT_EXPENSE"
export const EDIT_EXPENSE_SUCCESS = "EDIT_EXPENSE_SUCCESS"
export const EDIT_EXPENSE_FAILED = "EDIT_EXPENSE_FAILED"

export const DELETE_EXPENSE = "DELETE_EXPENSE"
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS"
export const DELETE_EXPENSE_FAILED = "DELETE_EXPENSE_FAILED"

export const EXPENSE_DETAIL = "EXPENSE_DETAIL"
export const EXPENSE_DETAIL_SUCCESS = "EXPENSE_DETAIL_SUCCESS"
export const EXPENSE_DETAIL_FAILED = "EXPENSE_DETAIL_FAILED"

export const FETCH_BUDGET = "FETCH_BUDGET"
export const FETCH_BUDGET_SUCCESS = "FETCH_BUDGET_SUCCESS"
export const FETCH_BUDGET_FAILED = "FETCH_BUDGET_FAILED"

export const BUDGET_DETAIL = "BUDGET_DETAIL"
export const BUDGET_DETAIL_SUCCESS = "BUDGET_DETAIL_SUCCESS"
export const BUDGET_DETAIL_FAILED = "BUDGET_DETAIL_FAILED"

export const ADD_BUDGET = "ADD_BUDGET"
export const ADD_BUDGET_FAILED = "ADD_BUDGET_FAILED"
export const ADD_BUDGET_SUCCESS = "ADD_BUDGET_SUCCESS"

export const ADD_BUDGET_EXPENSE = "ADD_BUDGET_EXPENSE"
export const ADD_BUDGET_EXPENSE_FAILED = "ADD_BUDGET_EXPENSE_FAILED"
export const ADD_BUDGET_EXPENSE_SUCCESS = "ADD_BUDGET_EXPENSE_SUCCESS"

export const EDIT_ADD_INCOME = "EDIT_ADD_INCOME"
export const EDIT_ADD_INCOME_SUCCESS = "EDIT_ADD_INCOME_SUCCESS"
export const EDIT_ADD_INCOME_FAILED = "EDIT_ADD_INCOME_FAILED"

export const EDIT_ADD_EXPENSE = "EDIT_ADD_EXPENSE"
export const EDIT_ADD_EXPENSE_SUCCESS = "EDIT_ADD_EXPENSE_SUCCESS"
export const EDIT_ADD_EXPENSE_FAILED = "EDIT_ADD_EXPENSE_FAILED"

export const DELETE_BUDGET = "DELETE_BUDGET"


export const INCOME_CSV_SUCCESS = "INCOME_CSV_SUCCESS"
export const INCOME_CSV_FAILED = "INCOME_CSV_FAILED"

export const EXPENSE_CSV_SUCCESS = "EXPENSE_CSV_SUCCESS"
export const EXPENSE_CSV_FAILED = "EXPENSE_CSV_SUCCESS"

export const ADD_AVATAR = "ADD_AVATAR"
export const ADD_AVATAR_SUCCESS = "ADD_AVATAR_SUCCESS"
export const ADD_AVATAR_FAILED = "ADD_AVATAR_FAILED"

export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILED = "DELETE_USER_FAILED"

export const DELETE_INCOME_BUDGET = 'DELETE_INCOME_BUDGET'
export const DELETE_INCOME_BUDGET_SUCCESS = 'DELETE_INCOME_BUDGET_SUCCESS'
export const DELETE_INCOME_BUDGET_FAILED = 'DELETE_INCOME_BUDGET_FAILED'

export const DELETE_EXPENSE_BUDGET = 'DELETE_EXPENSE_BUDGET'
export const DELETE_EXPENSE_BUDGET_FAILED = 'DELETE_EXPENSE_BUDGET_FAILED'
export const DELETE_EXPENSE_BUDGET_SUCCESS = 'DELETE_EXPENSE_BUDGET_SUCCESS'

export const GET_REPORT = "GET_REPORT"
export const GET_REPORT_FAILED = "GET_REPORT_FAILED"
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED"